// <auto-generated />
using CheesyApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CheesyApi.Migrations
{
    [DbContext(typeof(CheeseContext))]
    [Migration("20210715125647_SeedCheeses")]
    partial class SeedCheeses
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("CheesyApi.Models.Cheese", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Argb")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Color");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PricePerKilogram")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cheese");
                });
#pragma warning restore 612, 618
        }
    }
}
